### ISSUE TITLE
Segementation fault when running test.region.similarity.R 

### ISSUE THREAD

**Issue by whelena** [uclahs-cds/package-bedr#4]
When testing the public-R-bedr package, I ran into an error when building the vignette that traces back to
test.region.similarity.R  script on line 69.
```
perm.results <- mclapply(...)
```

it gives the following error:
```
segmentation fault
Error in bedr(engine = "bedtools", input = list(a = x, b = y), method = "reldist",  :
In addition: Warning message:
In system(command, wait = TRUE, intern = intern, ignore.stdout = FALSE,  :
running command 'bedtools reldist -a /tmp/RtmpxT5wu9/a_1fb74ae24ca7.bed -b /tmp/RtmpxT5wu9/b_1fb744111522.bed ' had status 139
```
 
 I think the reason why I haven't seen this error before on github or locally was because I was testing without bedtools and tabix installed and so when the vignette runs, it skips this function because the check.binary('bedtools') returns FALSE

**Comment by whelena** [comment]
I tried it on the F32 node and I still receive the same errors.

**Comment by tyamaguchi-ucla** [comment]
Are you using docker or mamba/conda R environment?

**Comment by whelena** [comment]
I used docker, with R 4.1.1. Is there anyone in the lab who have used or worked with the package before?

**Comment by tyamaguchi-ucla** [comment]
Probably Lydia, Adriana, Julie and me. Can you try out conda/mamba and see if you still see the issue?

https://confluence.mednet.ucla.edu/pages/viewpage.action?pageId=106106530

**Comment by tyamaguchi-ucla** [comment]
Also, you could use conda/mamba and see if you still get the same error?

https://confluence.mednet.ucla.edu/pages/viewpage.action?pageId=106106530

**Comment by whelena** [comment]
I didn't get any errors with conda /mamba!!

I ran it on the F2 node and was abble to build the package with no issue.
`R CMD check --as-cran --run-donttest bedr_*.tar.gz` also seemed to have run successfully.

Is there a reason why docker fails to build this package?

**Comment by whelena** [comment]
It works with conda/mamba!!

I was able to run `R CMD build` and working on resolving the errors and warning I get when I run `R CMD check --as-cran`

**Comment by whelena** [comment]
I'm working on a new dockerfile specifically for runninr bedr. I keep getting the same segmentation fault error and some googling suggest that it might have something to do with the host setting for `vm.overcommit_memory`.

When I run
```
(base) [username]$ sysctl vm.overcommit_memory
vm.overcommit_memory = 0
```
and when I try to set it to 1 (recommended by other users), I get
```
(base)  [username]$ sysctl vm.overcommit_memory=1
sysctl: permission denied on key 'vm.overcommit_memory'
```

**Comment by dan-knight** [comment]
That sounds promising. Are you trying to change `overcommit_memory` inside a running container or in a Dockerfile? If the former, try running the container with the `—privileged` flag.

**Comment by whelena** [comment]
Okay that did not solve the segmentation fault error ... 
I tried changing it in the dockerfile by adding:
`RUN sysctl vm.overcommit_memory=1`
 but that gives me this error when building
`sysctl: setting key "vm.overcommit_memory", ignoring: Read-only file system`

**Comment by tyamaguchi-ucla** [comment]
Maybe related to permission - what was your docker command to run an interactive or non-interactive session? (this info should be in the issue template)

**Comment by whelena** [comment]
I ran it using `docker run --it -v $(pwd):/usr/src/app/ bedr:test /bin/bash`

**Comment by tyamaguchi-ucla** [comment]
Ok, so you ran the image as root.. Can you point us to the Dockerfile and image? Also, what was the R command used in the interactive session?

**Comment by whelena** [comment]
Should I be running it as hwinata?

The Dockerfile is in `/hot/users/hwinata/docker/r_bedr/`

In the interactive session I ran `devtools::test()` and to build it I ran these from outside the package directory:
```
R CMD build --compact-vignettes="gs+qpdf" public-R-bedr
R CMD check --as-cran --run-donttest bedr_*.tar.gz
```

**Comment by tyamaguchi-ucla** [comment]
> The Dockerfile is in `/hot/users/hwinata/docker/r_bedr/`

Can you make a PR (I see the repo but don't see the file)? I have a few suggestions.

We're adding a PR template to the docker template repo soon but for now, you can use this PR template.
https://github.com/uclahs-cds/docker-bam-readcount/blob/main/.github/PULL_REQUEST_TEMPLATE.md

**Comment by whelena** [comment]
Here it is: https://github.com/uclahs-cds/docker-bedr/pull/1

it's not refined yet since I am using this container to test and build bedr.

**Comment by dan-knight** [comment]
> Here it is: [uclahs-cds/docker-bedr#1](https://github.com/uclahs-cds/docker-bedr/pull/1)
> 
> it's not refined yet since I am using this container to test and build bedr.

@whelena Is this fixed in the package too? We may have just forgotten to close this issue.
